/**
 * Mode B asset pipeline: generate -> validate -> optimise -> budget/pivot/animation checks ->
 * preview render -> manifest. Assets that fail any step are NOT copied to public/assets.
 *
 * Usage: npm run assets [-- <asset id> ...]
 */
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { type Document, NodeIO } from '@gltf-transform/core';
import { EXTMeshoptCompression, KHRMeshQuantization } from '@gltf-transform/extensions';
import { dedup, meshopt, prune, weld } from '@gltf-transform/functions';
import { validateBytes, type ValidationReport } from 'gltf-validator';
import { MeshoptDecoder, MeshoptEncoder } from 'meshoptimizer';
import { BUDGETS } from './budgets';
import type { AssetDef } from './defs/types';
import { boundsOf, evaluateScene, type Bounds, type Triangle } from './lib/evaluate';
import { encodePng } from './lib/png';
import { composeSheet, renderTile, type View } from './lib/render';
import { ASSETS } from './registry';

const WEB_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const OUT_DIR = join(WEB_ROOT, 'public/assets');
const PREVIEW_DIR = join(WEB_ROOT, 'asset-previews');
const MANIFEST_PATH = join(OUT_DIR, 'manifest.json');
const LICENSE = 'CC0-1.0 (original procedural asset generated by tools/assets)';
const TILE = 256;
const VIEWS: View[] = [
  { yawDeg: 180, elevationDeg: 12, label: 'front' },
  { yawDeg: 225, elevationDeg: 25, label: 'three-quarter' },
  { yawDeg: 90, elevationDeg: 8, label: 'side' },
  { yawDeg: 0, elevationDeg: 25, label: 'back' },
  { yawDeg: 180, elevationDeg: 55, label: 'game-camera' },
];
const PIVOT_TOLERANCE = 0.02;
const QUANTIZATION_TOLERANCE = 0.01;

interface ManifestEntry {
  id: string;
  path: string;
  category: string;
  tags: string[];
  triangles: number;
  drawCalls: number;
  materials: number;
  bytes: number;
  bones: number;
  animations: { name: string; duration: number }[];
  nodes: string[];
  bounds: Bounds;
  collider: AssetDef['collider'];
  license: string;
  preview: string;
  meta?: Record<string, unknown>;
}

interface Result {
  id: string;
  errors: string[];
  warnings: string[];
  entry?: ManifestEntry;
  glb?: Uint8Array;
}

const round = (value: number, digits = 3) => Number(value.toFixed(digits));
const roundBounds = (bounds: Bounds): Bounds => ({
  min: bounds.min.map((v) => round(v)) as Bounds['min'],
  max: bounds.max.map((v) => round(v)) as Bounds['max'],
});

async function createIO(): Promise<NodeIO> {
  await MeshoptEncoder.ready;
  await MeshoptDecoder.ready;
  return new NodeIO()
    .registerExtensions([EXTMeshoptCompression, KHRMeshQuantization])
    .registerDependencies({ 'meshopt.encoder': MeshoptEncoder, 'meshopt.decoder': MeshoptDecoder });
}

function summarizeValidation(report: ValidationReport, stage: string, result: Result): void {
  for (const message of report.issues.messages) {
    const text = `[${stage}] ${message.code}: ${message.message}${message.pointer ? ` (${message.pointer})` : ''}`;
    if (message.severity === 0) result.errors.push(text);
    else if (message.severity === 1) result.warnings.push(text);
  }
}

function countStats(doc: Document) {
  let triangles = 0;
  let drawCalls = 0;
  const materials = new Set<unknown>();
  const scene = doc.getRoot().getDefaultScene();
  scene?.traverse((node) => {
    for (const primitive of node.getMesh()?.listPrimitives() ?? []) {
      drawCalls += 1;
      const indices = primitive.getIndices();
      triangles += (indices ? indices.getCount() : (primitive.getAttribute('POSITION')?.getCount() ?? 0)) / 3;
      materials.add(primitive.getMaterial());
    }
  });
  const bones = Math.max(0, ...doc.getRoot().listSkins().map((skin) => skin.listJoints().length));
  return { triangles, drawCalls, materials: materials.size, bones };
}

function checkLoops(doc: Document, result: Result): void {
  for (const animation of doc.getRoot().listAnimations()) {
    for (const sampler of animation.listSamplers()) {
      const output = sampler.getOutput();
      const input = sampler.getInput();
      if (!output || !input || output.getCount() < 2) continue;
      const first = output.getElement(0, []);
      const last = output.getElement(output.getCount() - 1, []);
      const sign = output.getElementSize() === 4 && first.reduce((acc, v, i) => acc + v * (last[i] ?? 0), 0) < 0 ? -1 : 1;
      const delta = Math.max(...first.map((v, i) => Math.abs(v - sign * (last[i] ?? 0))));
      if (delta > 1e-3) result.errors.push(`Clip ${animation.getName()} does not loop seamlessly (delta ${delta.toFixed(4)})`);
    }
  }
}

function checkPivot(bounds: Bounds, result: Result): void {
  if (Math.abs(bounds.min[1]) > PIVOT_TOLERANCE) result.errors.push(`Pivot not at base: min Y = ${bounds.min[1].toFixed(3)}`);
  const containsOrigin = bounds.min[0] <= 0 && bounds.max[0] >= 0 && bounds.min[2] <= 0 && bounds.max[2] >= 0;
  if (!containsOrigin) result.errors.push('Pivot (0,0,0) lies outside the XZ footprint');
}

async function processAsset(def: AssetDef, io: NodeIO, built: Map<string, Document>): Promise<Result> {
  const result: Result = { id: def.id, errors: [], warnings: [] };
  const budget = BUDGETS[def.category];

  const source = def.build();
  built.set(def.id, source);
  summarizeValidation(await validateBytes(await io.writeBinary(source), { uri: `${def.id}.glb`, maxIssues: 50 }), 'raw', result);

  const clipNames = source.getRoot().listAnimations().map((a) => a.getName());
  for (const clip of def.requiredAnimations ?? []) if (!clipNames.includes(clip)) result.errors.push(`Missing clip ${clip}`);
  const nodeNames = source.getRoot().listNodes().map((n) => n.getName());
  for (const name of def.requiredNodes ?? []) if (!nodeNames.includes(name)) result.errors.push(`Missing node ${name}`);
  checkLoops(source, result);

  const restClip = clipNames.includes('anim_Idle') ? 'anim_Idle' : undefined;
  const sourceTriangles = evaluateScene(source, restClip, 0);
  const sourceBounds = boundsOf(sourceTriangles);
  checkPivot(sourceBounds, result);

  const optimized = (await io.readBinary(await io.writeBinary(source))).setLogger(source.getLogger());
  await optimized.transform(dedup(), prune(), weld(), meshopt({ encoder: MeshoptEncoder, level: 'medium' }));
  const glb = await io.writeBinary(optimized);
  summarizeValidation(await validateBytes(glb, { uri: `${def.id}.glb`, maxIssues: 50 }), 'final', result);

  const reloaded = await io.readBinary(glb);
  const finalBounds = boundsOf(evaluateScene(reloaded, restClip, 0));
  const drift = Math.max(...[0, 1, 2].flatMap((k) => [Math.abs(finalBounds.min[k]! - sourceBounds.min[k]!), Math.abs(finalBounds.max[k]! - sourceBounds.max[k]!)]));
  if (drift > QUANTIZATION_TOLERANCE) result.errors.push(`Optimised geometry drifted ${drift.toFixed(4)} m from source`);

  const stats = countStats(reloaded);
  if (stats.triangles > budget.maxTriangles) result.errors.push(`Triangles ${stats.triangles} > ${budget.maxTriangles}`);
  if (stats.materials > budget.maxMaterials) result.errors.push(`Materials ${stats.materials} > ${budget.maxMaterials}`);
  if (stats.drawCalls > budget.maxDrawCalls) result.errors.push(`Draw calls ${stats.drawCalls} > ${budget.maxDrawCalls}`);
  if (glb.byteLength > budget.maxBytes) result.errors.push(`Size ${glb.byteLength} B > ${budget.maxBytes} B`);
  if (budget.maxBones !== undefined && stats.bones > budget.maxBones) result.errors.push(`Bones ${stats.bones} > ${budget.maxBones}`);
  if (reloaded.getRoot().listTextures().length > 0) result.errors.push('Textures present; Mode B assets must use vertex colours');

  const tiles = VIEWS.map((view) => renderTile(sourceTriangles, view, TILE));
  for (const pose of def.previews ?? []) {
    let triangles: Triangle[] = evaluateScene(source, pose.clip, pose.phase);
    if (pose.with) {
      const companion = built.get(pose.with);
      if (!companion) result.warnings.push(`Preview companion ${pose.with} not built yet`);
      else triangles = [...triangles, ...evaluateScene(companion)];
    }
    tiles.push(renderTile(triangles, { yawDeg: 90, elevationDeg: 10 }, TILE));
    tiles.push(renderTile(triangles, { yawDeg: 200, elevationDeg: 20 }, TILE));
  }
  const sheet = composeSheet(tiles, TILE, 5);
  const previewPath = join(PREVIEW_DIR, `${def.id}.png`);
  await writeFile(previewPath, encodePng(sheet.width, sheet.height, sheet.rgb));

  result.glb = glb;
  result.entry = {
    id: def.id,
    path: `assets/${def.id}.glb`,
    category: def.category,
    tags: def.tags,
    triangles: stats.triangles,
    drawCalls: stats.drawCalls,
    materials: stats.materials,
    bytes: glb.byteLength,
    bones: stats.bones,
    animations: reloaded.getRoot().listAnimations().map((a) => ({
      name: a.getName(),
      duration: round(Math.max(0, ...a.listSamplers().map((s) => s.getInput()?.getMax([])[0] ?? 0))),
    })),
    nodes: reloaded.getRoot().listNodes().map((n) => n.getName()).filter((n) => !n.startsWith('bone_')),
    bounds: roundBounds(finalBounds),
    collider: def.collider,
    license: LICENSE,
    preview: `asset-previews/${def.id}.png`,
    ...(def.meta ? { meta: def.meta } : {}),
  };
  return result;
}

async function main(): Promise<void> {
  const only = process.argv.slice(2).filter((arg) => !arg.startsWith('-'));
  const selected = only.length ? ASSETS.filter((a) => only.includes(a.id)) : ASSETS;
  const ordered = [...selected].sort((a, b) => Number(a.category === 'hero' || a.category === 'npc') - Number(b.category === 'hero' || b.category === 'npc'));
  await mkdir(OUT_DIR, { recursive: true });
  await mkdir(PREVIEW_DIR, { recursive: true });

  const io = await createIO();
  const built = new Map<string, Document>();
  for (const def of ASSETS) if (!selected.includes(def) && def.category.startsWith('vehicle')) built.set(def.id, def.build());

  const previous: { assets: ManifestEntry[] } = await readFile(MANIFEST_PATH, 'utf8').then((t) => JSON.parse(t) as { assets: ManifestEntry[] }).catch(() => ({ assets: [] }));
  const entries = new Map(previous.assets.map((e) => [e.id, e]));
  let failed = 0;

  for (const def of ordered) {
    const result = await processAsset(def, io, built).catch((error: unknown): Result => ({ id: def.id, errors: [String(error)], warnings: [] }));
    const status = result.errors.length ? 'FAIL' : 'PASS';
    const e = result.entry;
    console.log(`${status} ${def.id.padEnd(20)} ${e ? `${String(e.triangles).padStart(5)} tri  ${e.drawCalls} dc  ${e.materials} mat  ${(e.bytes / 1024).toFixed(1).padStart(6)} KB  ${e.bones} bones  ${e.animations.length} clips` : ''}`);
    for (const warning of result.warnings) console.log(`     warn  ${warning}`);
    for (const error of result.errors) console.log(`     error ${error}`);

    const target = join(OUT_DIR, `${def.id}.glb`);
    if (result.errors.length || !result.glb || !result.entry) {
      failed += 1;
      entries.delete(def.id);
      await rm(target, { force: true });
      continue;
    }
    await writeFile(target, result.glb);
    entries.set(def.id, result.entry);
  }

  const manifest = { version: 1, generatedBy: 'tools/assets/build.ts', assets: [...entries.values()].sort((a, b) => a.id.localeCompare(b.id)) };
  await writeFile(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`);
  console.log(`\n${selected.length - failed}/${selected.length} assets passed. Manifest: public/assets/manifest.json`);
  if (failed) process.exitCode = 1;
}

await main();